export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const KAKAO_REGISTER = "KAKAO_REGISTER";
export const KAKAO_UNLINK = "KAKAO_UNLINK";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCH_DIARIES = "FETCH_DIARIES";

